name: Build TWRP Recovery

on:
  watch:
    types: [started]

  workflow_dispatch:
    inputs:
      manifest:
          description: 'Recovery Manifest'
          required: true
          default: 'https://github.com/minimal-manifest-twrp/platform_manifest_twrp_aosp'
      manifestbranch:
          description: 'Manifest Branch'
          required: true
          default: 'twrp-12.1'
      devicerepo:
          description: 'Device Tree Source'
          required: true
      devicebranch:
          description: 'Device Tree Branch'
          required: true
      devicepath:
          description: 'Device Path'
          required: true
          default: 'device/xiaomi/Mi8953v1'
      devicename:
          description: 'Device Codename'
          required: true
      makefile:
          description: 'Makefile Name'
          required: true
          default: 'twrp_Mi8953v1'
      makewhat:
          description: 'recovery/boot'
          required: true
          default: 'recovery'
        
jobs:
  Build:
    if: github.event.repository.owner.id == github.event.sender.id
    runs-on: ubuntu-20.04
    env:
      TZ: Asia/Jakarta

      builddate: "${{ needs.Set-repos.outputs.builddate }}"

      TZ: Asia/Jakarta
      DEVICENAME: ${{ github.event.inputs.devicename }}
      DEVICEPATH: ${{ github.event.inputs.devicepath }}
      DEVICEREPO: ${{ github.event.inputs.devicerepo }}
      DEVICEBRANCH: ${{ github.event.inputs.devicebranch }}
      MANIFEST: ${{ github.event.inputs.manifest }}
      MANIFESTBRANCH: ${{ github.event.inputs.manifestbranch }}
      MAKEFILE: ${{ github.event.inputs.makefile }}
      MAKEWHAT: ${{ github.event.inputs.makewhat }}

    steps:
      - name: Remove Useless Package
        run: |
          wget https://raw.githubusercontent.com/KanariaAlt/Android-CI/main/Common/free_disk_space.sh
          bash free_disk_space.sh
        
      - name: Set Swap Space
        uses: pierotofy/set-swap-space@master
        with:
          swap-size-gb: 12

      - name: Prepare Environment
        run: |
          export HOME=${GITHUB_WORKSPACE}
          cd ${GITHUB_WORKSPACE}
          wget https://raw.githubusercontent.com/KanariaAlt/Android-CI/main/Common/Dependency.sh
          bash Dependency.sh

      - name: Install OpenJDK
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '11'

      - name: Install repo
        run: |
          wget https://raw.githubusercontent.com/KanariaAlt/Android-CI/main/Common/Install_Repo.sh
          bash Install_Repo.sh

      - name: Init Repo
        run: |
          mkdir ${GITHUB_WORKSPACE}/workspace
          cd ${GITHUB_WORKSPACE}/workspace
          wget https://raw.githubusercontent.com/KanariaAlt/Android-CI/main/Common/Git-Config.sh
          bash Git-Config.sh
          repo init --depth=1 -u $MANIFEST -b $MANIFESTBRANCH
        
      - name: Repo Sync
        run: |
          cd ${GITHUB_WORKSPACE}/workspace
          repo sync -j4
  
      - name: Clone Device Tree
        run: |
          cd ${GITHUB_WORKSPACE}/workspace
          git clone $DEVICEREPO -b $DEVICEBRANCH $DEVICEPATH
        
      - name: Building recovery
        run: |
          cd ${GITHUB_WORKSPACE}/workspace
          . build/envsetup.sh
          lunch $MAKEFILE-eng
          echo "BUILDTIME=$(TZ=Asia/Shanghai date "+%Y%m%d%H%M")" >> $GITHUB_ENV
          mka $MAKEWHATimage -j4

      - name: Upload $MAKEWHAT image
        uses: actions/upload-artifact@v3
        with:
          name: $MAKEWHAT-$DEVICENAME-$BUILDTIME
          path: workspace/out/target/product/$DEVICENAME/$MAKEWHAT.img